name: Build Naruto Mod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 0.3.2-beta

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Build
        run: .\gradlew.bat clean build --refresh-dependencies --no-daemon

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: NarutoMod-build
          path: build/libs/*.jar
